[package]
name = "ferris-cms"
version = "0.1.0"
edition = "2021"

[dependencies]
html-escape = "0.2.13"
markdown = "1.0.0-alpha.21"
serde = { version = "1.0.215", features = ["serde_derive"] }
tiny_http = "0.12.0"
toml = "0.8.19"
